### PR TITLE
Fixes for Webpack 5

### PR DESCRIPTION
**Pull request by Dishwasha**

### CODE REVIEW

**Comment by Dishwasha** [comment]
In response to comments made in https://github.com/single-spa/vue-cli-plugin-single-spa/pull/28

**Comment by Dishwasha** [comment]
bump

**Comment by Dishwasha** [comment]
bump

**Comment by jasonatball** [comment]
Now that [vue-cli v5](https://github.com/vuejs/vue-cli/releases/tag/v5.0.1) is out it would be really good to get this compatibility with Webpack 5. Thanks!

**Comment by Dishwasha** [comment]
It's been 4 months.  I'm now forced to fork this project and release my own version.

**Comment by jasonatball** [comment]
@joeldenning @filoxo @Lalaluka could one of you guys approve this so this project can support vue-cli v5? Thank you!

**Comment by Lalaluka** [comment]
@jasonatball I'm not a part of the single-spa core team and I don't have write access to this repo. So my approval won't help.

**Comment by filoxo** [comment]
@jasonatball thanks for bringing this up again. I'll consult with the rest of the core team and hopefully merge today. I personally haven't been able to test this but given @Dishwasha's usage of their changes that has been working for a long time now, I'd like to think that that's validation enough unless anyone has concerns still.

**Review by TheMcMurder — APPROVED** [review]

**Comment by jasonatball** [comment]
Thanks everyone for helping get this merged so quickly!

**Pull request merged**
